# Generated by Django 3.0.7 on 2021-11-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211121_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='bank',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='BankTransaction',
        ),
    ]
