# Generated by Django 3.0.7 on 2021-09-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproduct',
            old_name='cost_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='sell_price',
        ),
    ]
