# Generated by Django 3.0.7 on 2021-09-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210906_1611'),
        ('purchase', '0002_auto_20210906_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='product_name',
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
            preserve_default=False,
        ),
    ]
