# Generated by Django 3.0.7 on 2021-09-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20210906_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='warehouse',
        ),
    ]
