# Generated by Django 3.0.7 on 2021-11-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20210908_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='check_date',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='check_no',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='payment_type',
        ),
    ]
