# Generated by Django 3.0.7 on 2021-11-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_auto_20210908_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproductitem',
            name='sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sell.Sell'),
        ),
    ]
