# Generated by Django 3.0.7 on 2021-12-10 14:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211126_1316'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sell', '0007_auto_20211126_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.BooleanField(default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sell.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='sellproductitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sellproductitem',
            name='sell',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.DeleteModel(
            name='SellProductItem',
        ),
    ]
